-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."sessions" add column "isValid" bool
--  not null default 'true';
